### ISSUE TITLE
No Schematic Library?

### ISSUE THREAD

**Issue by BigJonas** [ai03-2725/MX_V2#1]
I've been using this for some projects but I also have to use the old library because it has the schematics. Are there plans to add schematic libraries to this project or will I continue to have to use the old schematic library.

**Comment by ai03-2725** [comment]
As per the readme, it is on the todo.
I currently see no issue with it - the stock `sw_push` and similar simple two-pin symbols are fully compatible as a switch is only a simple two-pin device.
